### ISSUE TITLE
Review of changes in kubernetes.conf

### ISSUE THREAD

**Issue by emrocha** [fluent/fluentd-kubernetes-daemonset#384]
In commit 06b0a08c0261477d8eee2ccf2cdd0d4f7b864afe the following lines have been added to the docker-image/v1.7/debian-XXX/conf/kubernetes.conf files.

```
kubernetes_url` "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || https://#{ENV.fetch('KUBERNETES_SERVICE_HOST')}:#{ENV.fetch('KUBERNETES_SERVICE_PORT')}/api}"
verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
ca_file "#{ENV['KUBERNETES_CA_FILE']}"
```

After that, my Pods stopped working. They start but display no output and do not start log collections.

I replaced 

`kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || https://#{ENV.fetch('KUBERNETES_SERVICE_HOST')}:#{ENV.fetch('KUBERNETES_SERVICE_PORT')}/api}"
`

by

`kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV['KUBERNETES_SERVICE_HOST'] + ':' + ENV['KUBERNETES_SERVICE_PORT'] + '/api' }"
`

It didn't look pretty, but it worked.

Could you review this commit?

Thank you

**Comment by jpugliesi** [comment]
We are experiencing the same symptoms described above by @emrocha  - fluentd pods do not produce any logs to stdout and `ruby` utilizes 100% of the CPU on the kubernetes node.

We were able to mitigate by pinning the daemonset image to `v1.7.4-debian-elasticsearch7-1.0` (instead of the latest image)

**Comment by repeatedly** [comment]
@emrocha Good catch. Your change is good. Need to quote string with `"` for ruby string.

**Comment by bbcnt** [comment]
Had exactly the same issue, changing this file also worked for me. Thanks mate, that saved me a lot of time.

**Comment by repeatedly** [comment]
We have published 2.2 images with this fix.
Check it.

**Comment by ninja-** [comment]
@repeatedly I am running from tag v1.7.4-debian-graylog-2.2 and the problem is still here ehhhhhhhhh

**Comment by ninja-** [comment]
@repeatedly I think you meant to modify the line, not add another one in the patch

**Comment by ninja-** [comment]
@repeatedly yeah, when I fix the duplicated line it starts working. please fix your patch

**Comment by repeatedly** [comment]
@ninja Please send the patch.

**Comment by repeatedly** [comment]
Okay. Just removed the line and now building new images: https://github.com/fluent/fluentd-kubernetes-daemonset/commit/08fcd8fc92cdc7313f29aafe6f1bf01ccafca035

**Comment by ninja-** [comment]
thanks
